services:
  serenade-ros-dev:
    build:
      context: ../../
      dockerfile: Dockerfile
      network: host
    image: orbslam3_ros:v12
    container_name: serenade-ros-dev
    hostname: orbslam3
    network_mode: "host"
    privileged: true
    environment:
      - TZ=Asia/Hong_Kong
      - ROS_HOSTNAME=orbslam3
      - ROS_MASTER_URI=http://orbslam3:11311
      - DISPLAY=:1
      - QT_X11_NO_MITSHM=1
    volumes:
      - .:/overlay_ws/src/serenade:cached
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/localtime:/etc/localtime:ro
    command: /bin/sh -c "while sleep 1000; do :; done"
    tty: true
    stdin_open: true
